# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ba02f3eebb002ecd89ef78a2a173d243a7ed3a338042f21b98f52d9d9280d7ceabe3e51152119ad8f738d59f2d741f9c87186108d1b5057bc24e022c08fef37

test:
  secret_key_base: 33464b64ae2b66ef870ecc6ce1c1fec7a5357ccc2d21551357864e36941cef5402a9f73f1286f416c5aafbd5587dbc03c3190f2e8cce3dfd9ee751c5eaa9b758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
